branch-defaults:
  default:
    environment: nosto-dev
    group_suffix: null
deploy:
  artifact: build/libs/rest-service-0.0.1-SNAPSHOT.jar
global:
  application_name: nosto
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
